var animal_list = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Donkey",
    "Baboon",
    "Badger",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bison",
    "Boar",
    "Buffalo",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caribou",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Clam",
    "Cobra",
    "Cockroach",
    "Cod",
    "Cormorant",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Deer",
    "Dinosaur",
    "Dog",
    "Dolphin",
    "Dove",
    "Dragonfly",
    "Duck",
    "Eagle",
    "Eel",
    "Elephant",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Fish",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gazelle",
    "Gerbil",
    "Giraffe",
    "Gnat",
    "Goat",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Grasshopper",
    "Gull",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Hummingbird",
    "Jackal",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Manatee",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mouse",
    "Mule",
    "Narwhal",
    "Newt",
    "Octopus",
    "Opossum",
    "Ostrich",
    "Otter",
    "Owl",
    "Oyster",
    "Panda",
    "Panther",
    "Parrot",
    "Partridge",
    "Peacock",
    "Pelican",
    "Penguin",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Quail",
    "Rabbit",
    "Raccoon",
    "Ram",
    "Rat",
    "Raven",
    "Reindeer",
    "Rhinoceros",
    "Salamander",
    "Salmon",
    "Scorpion",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Skunk",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Squid",
    "Squirrel",
    "Stingray",
    "Stork",
    "Swan",
    "Tapir",
    "Tiger",
    "Toad",
    "Turkey",
    "Turtle",
    "Vulture",
    "Walrus",
    "Weasel",
    "Whale",
    "Wolf",
    "Woodpecker",
    "Worm",
    "Yak",
    "Zebra"
];

// find longest words in array to determine max-width of wordbox

var length = Array.from(animal_list, animal => [animal, animal.length])

console.log(length);

length.sort(function (a, b) {
  return b[1] - a[1];
})

//hippopotamus Caterpillar is the longest combo

var size = animal_list.length;

// console.log(animal_list);
// console.log(size);

function PickRandomWord(frm) {
// Generate a random number between 1 and animal_list.length
var rnd = Math.ceil(Math.random() * size);
// console.log(animal_list[rnd]);

var rnd2 = Math.ceil(Math.random() * size);

while (rnd == rnd2) {
  rnd2 = Math.ceil(Math.random() * size)
}

// bleh = 'animal_list[rnd] animal_list[rnd2]'
// Display the word inside the text box
frm.WordBox.value = animal_list[rnd] + ' ' + animal_list[rnd2]
};
